{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - secrets
  resourceNames:
    - cluster-ca
    - cluster-default-ssl
  verbs:
    - "create"
    - "get"
    - "delete"
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - "create"
{{- end -}}
